// cards_market.js
// All recruitable hero cards available in the Market pool.
// Cards are type 'hero' and have a non-zero cost.
// Do not add engine logic to this file.
// Calls Registry.register_cards_market() — registry.js must load first.

Registry.register_cards_market([

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — Level 1
  // ─────────────────────────────────────────────────────────────

  {
    id:       'soldier',
    role:     'physical',
    level:    1,
    name:     "FIGHTER (Champion)",
    type:     'hero',
    cost:     3,
    atk:      5,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "A Champion fighter — pure martial skill, every blow seeks the kill. Deal 5 Physical damage.",
    art:      make_art_painter('physical'),
  },

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — Level 2
  // ─────────────────────────────────────────────────────────────

  {
    id:       'spearman',
    role:     'physical',
    level:    2,
    name:     "FIGHTER (Cavalier)",
    type:     'hero',
    cost:     3,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   2,
    effects:  [],
    desc:     "A Cavalier holds the line on horse and lance. Deal 4 Physical damage. Gain 2 Defence.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'outrider',
    role:     'physical',
    level:    2,
    name:     "RANGER (Hunter)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "A Ranger Hunter scouts ahead. Deal 2 Physical damage. Draw 1 card.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'novice_brawler',
    role:     'physical',
    level:    2,
    name:     "MONK (Open Hand)",
    type:     'hero',
    cost:     2,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "Open Hand palm strike — Stun a random Monster.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'sentinel',
    role:     'physical',
    level:    2,
    name:     "PALADIN (Devotion)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   3,
    effects:  [
      { type: 'scrap', target: 'starter' },
    ],
    desc:     "Devotion purges what is impure. Gain 3 Defence. Scrap a random Starter from your deck.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'recruiter',
    role:     'physical',
    level:    2,
    name:     "FIGHTER (Purple Dragon)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      {
        type:         'transform',
        target:       { match: 'type', value: 'starter' },
        replace_with: 'soldier',
        zones:        ['field'],
        selection:    'random',
        fallback:     'none',
      },
    ],
    desc:     'Deal 2 Physical damage. Transform a random Starter on the field into a Soldier.',
    art:      make_art_painter('physical'),
  },

  {
    id:       'corsair',
    role:     'physical',
    level:    2,
    name:     "BARBARIAN (Battlerager)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'physical',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'shield_drain', amount: 2 },
    ],
    desc:     "Battlerager spiked armour rams home — knocks coin loose. Deal 2 Physical damage. Gain 2 Gold. Drain 2 Monster Shield.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'pike_guard',
    role:     'physical',
    level:    2,
    name:     "PALADIN (Watchers)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "Watchers' phalanx wards the supernatural. Deal 2 Physical damage. Stun all Monsters opposite this slot.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'berserker',
    role:     'physical',
    level:    2,
    name:     "BARBARIAN (Berserker)",
    type:     'hero',
    cost:     3,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   -2,
    shield:   0,
    effects:  [],
    desc:     "Berserker abandon — pure unbridled rage. Deal 4 Physical damage. Costs 2 Morale.",
    art:      make_art_painter('physical'),
  },

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — Level 3
  // ─────────────────────────────────────────────────────────────

  {
    id:       'veteran',
    role:     'physical',
    level:    3,
    name:     "FIGHTER (Battle Master)",
    type:     'hero',
    cost:     4,
    atk:      5,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      {
        type:      'field_bonus',
        condition: 'adjacent_role_match',
        stat:      'atk',
        amount:    2,
      },
    ],
    desc:     'Deal 5 Physical damage. +2 ATK if an adjacent Hero is also Physical.',
    art:      make_art_painter('physical'),
  },

  {
    id:       'duellist',
    role:     'physical',
    level:    3,
    name:     "FIGHTER (Samurai)",
    type:     'hero',
    cost:     4,
    atk:      3,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "A Samurai cuts down all who face him. Deal 3 Physical damage. Stun all opposite Monsters.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'war_priest',
    role:     'physical',
    level:    3,
    name:     "CLERIC (War Domain)",
    type:     'hero',
    cost:     4,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   2,
    shield:   0,
    effects:  [],
    desc:     "War Domain blessing — strike with holy fervour. Deal 4 Physical damage. Restore 2 Morale.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'blood_knight',
    role:     'physical',
    level:    3,
    name:     "PALADIN (Vengeance)",
    type:     'hero',
    cost:     4,
    atk:      6,
    atk_type: 'physical',
    gold:     0,
    morale:   -3,
    shield:   0,
    effects:  [],
    desc:     "Vengeance burns through every blow. Deal 6 Physical damage. Costs 3 Morale.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'gladiator',
    role:     'physical',
    level:    3,
    name:     "BARBARIAN (Zealot)",
    type:     'hero',
    cost:     5,
    atk:      8,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "A Zealot's fervour cannot be quenched. Deal 8 Physical damage.",
    art:      make_art_painter('physical'),
  },

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — Level 4
  // ─────────────────────────────────────────────────────────────

  {
    id:       'warbringer',
    role:     'physical',
    level:    4,
    name:     "BARBARIAN (Storm Herald)",
    type:     'hero',
    cost:     5,
    atk:      6,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stat_mod_all', stat: 'atk', amount: 1, duration: 'turn' },
    ],
    desc:     "Storm Herald summons the wrath of nature — all Heroes gain +1 ATK this turn. Deal 6 Physical damage.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'oath_knight',
    role:     'physical',
    level:    4,
    name:     "PALADIN (Ancients)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   2,
    shield:   5,
    effects:  [],
    desc:     "Ancients' grove protects the city. Deal 4 Physical damage. Gain 5 Defence. Restore 2 Morale.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'brawler',
    role:     'physical',
    level:    4,
    name:     "MONK (Drunken Master)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "Drunken Master — every stagger is a strike. Stun all opposite Monsters.",
    art:      make_art_painter('physical'),
  },

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — Level 5
  // ─────────────────────────────────────────────────────────────

  {
    id:       'dragonslayer',
    role:     'physical',
    level:    5,
    name:     "RANGER (Monster Slayer)",
    type:     'hero',
    cost:     6,
    atk:      10,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "A Monster Slayer fells beasts in a single stroke. Deal 10 Physical damage.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'apprentice',
    role:     'magical',
    level:    1,
    name:     "WIZARD (Evocation)",
    type:     'hero',
    cost:     2,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "An Evocation novice slings raw arcane fire. Deal 3 Magical damage.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'black_mage',
    role:     'magical',
    level:    1,
    name:     "WARLOCK (Fiend)",
    type:     'hero',
    cost:     3,
    atk:      4,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "Fiend's pact unleashes hellfire. Deal 4 Magical damage.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'white_mage',
    role:     'magical',
    level:    1,
    name:     "CLERIC (Life)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   3,
    shield:   0,
    effects:  [],
    desc:     "Life Domain mends every wound. Restore 3 Morale.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // MAGICAL — Level 2
  // ─────────────────────────────────────────────────────────────

  {
    id:       'conjurer',
    role:     'magical',
    level:    2,
    name:     "WIZARD (Conjuration)",
    type:     'hero',
    cost:     3,
    atk:      4,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "Conjuration calls reinforcements. Deal 4 Magical damage. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'runesmith',
    role:     'magical',
    level:    2,
    name:     "WIZARD (Abjuration)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   3,
    effects:  [],
    desc:     "Abjuration wards turn aside the worst. Deal 2 Magical damage. Gain 3 Defence.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'seer',
    role:     'magical',
    level:    2,
    name:     "WIZARD (Divination)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   3,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "Divination foresees harm and prevents it. Restore 3 Morale. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // MAGICAL — Level 3
  // ─────────────────────────────────────────────────────────────

  {
    id:       'hexblade',
    role:     'magical',
    level:    3,
    name:     "WARLOCK (Hexblade)",
    type:     'hero',
    cost:     4,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "Hexblade's curse paralyses prey. Deal 3 Magical damage. Stun a random Monster.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'enchantress',
    role:     'magical',
    level:    3,
    name:     "WIZARD (Enchantment)",
    type:     'hero',
    cost:     4,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'cost_reduce', amount: 2 },
    ],
    desc:     "Enchantment charms the seller. Deal 3 Magical damage. Your next recruit this turn costs 2 less Gold.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'war_mage',
    role:     'magical',
    level:    3,
    name:     "WIZARD (War Magic)",
    type:     'hero',
    cost:     4,
    atk:      5,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   2,
    effects:  [],
    desc:     "War Magic — combat-ready arcane focus. Deal 5 Magical damage. Gain 2 Defence.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'soul_binder',
    role:     'magical',
    level:    3,
    name:     "CLERIC (Grave)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   2,
    shield:   0,
    effects:  [
      { type: 'recur', selection: 'random', fallback: 'none' },
    ],
    desc:     "Grave Domain — death is not the end. Restore 2 Morale. Recall a random Hero from discard.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'necromancer',
    role:     'magical',
    level:    3,
    name:     "WIZARD (Necromancy)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'recur', selection: 'random', fallback: 'none' },
    ],
    desc:     "Necromancy raises a fallen ally. Recall a random Hero from discard.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // MAGICAL — Level 4
  // ─────────────────────────────────────────────────────────────

  {
    id:       'oracle',
    role:     'magical',
    level:    4,
    name:     "CLERIC (Knowledge)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   4,
    shield:   2,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "Knowledge Domain foretells weakness. Restore 4 Morale. Gain 2 Defence. Stun a random Monster.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'pyromancer',
    role:     'magical',
    level:    4,
    name:     "SORCERER (Draconic)",
    type:     'hero',
    cost:     5,
    atk:      7,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "Draconic Bloodline — dragon-breath. Deal 7 Magical damage. Stun a random Monster.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'chronomancer',
    role:     'magical',
    level:    4,
    name:     "WIZARD (Chronurgy)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'haste', target_side: 'monster' },
      { type: 'draw', amount: 1 },
    ],
    desc:     "Chronurgy bends time. Force a random Monster to act next. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'mind_breaker',
    role:     'magical',
    level:    4,
    name:     "SORCERER (Aberrant Mind)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stop', target_side: 'monster' },
      { type: 'weaken_atk', amount: 2 },
    ],
    desc:     "Aberrant Mind shatters the will. Stop a random Monster from acting. Weaken Big Bad ATK by 2 next turn.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'freeze_mage',
    role:     'magical',
    level:    4,
    name:     "SORCERER (Storm Sorcery)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "Storm Sorcery hailstorm. Stun all Monsters opposite this slot.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // MAGICAL — Level 5
  // ─────────────────────────────────────────────────────────────

  {
    id:       'grand_wizard',
    role:     'magical',
    level:    5,
    name:     "WIZARD (Order of Scribes)",
    type:     'hero',
    cost:     6,
    atk:      8,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "Order of Scribes — knowledge made weapon. Deal 8 Magical damage. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'storm_witch',
    role:     'magical',
    level:    5,
    name:     "SORCERER (Wild Magic)",
    type:     'hero',
    cost:     6,
    atk:      6,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "Wild Magic surge tears through the line. Deal 6 Magical damage. Stun all opposite Monsters.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'exorcist',
    role:     'magical',
    level:    5,
    name:     "CLERIC (Light)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'kill_monster', selection: 'random', fallback: 'none' },
    ],
    desc:     "Light Domain banishes evil utterly. Banish a random Monster type for the rest of the fight.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // TACTICAL — Level 1
  // ─────────────────────────────────────────────────────────────

  {
    id:       'merchant',
    role:     'tactical',
    level:    1,
    name:     "ROGUE (Mastermind)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     3,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "A Mastermind plays the market. Gain 3 Gold.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'fence',
    role:     'tactical',
    level:    1,
    name:     "ROGUE (Thief)",
    type:     'hero',
    cost:     2,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "A Thief's haul lines the pockets. Gain 2 Gold. Draw 1 card.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'scout',
    role:     'tactical',
    level:    1,
    name:     "ROGUE (Scout)",
    type:     'hero',
    cost:     2,
    atk:      0,
    atk_type: 'none',
    gold:     1,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'scrap', target: 'starter' },
    ],
    desc:     "A Scout culls the dead weight. Gain 1 Gold. Scrap a random Starter from your deck.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // TACTICAL — Level 2
  // ─────────────────────────────────────────────────────────────

  {
    id:       'informant',
    role:     'tactical',
    level:    2,
    name:     "ROGUE (Inquisitive)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     3,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'weaken_atk', amount: 1 },
    ],
    desc:     "Inquisitive eyes spot the pattern. Gain 3 Gold. Weaken Big Bad ATK by 1 next turn.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'alchemist',
    role:     'tactical',
    level:    2,
    name:     "ARTIFICER (Alchemist)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'cost_reduce', amount: 2 },
    ],
    desc:     "An Alchemist brews a single potion — your next recruit costs 2 less Gold. Gain 2 Gold.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // TACTICAL — Level 3
  // ─────────────────────────────────────────────────────────────

  {
    id:       'guildmaster',
    role:     'tactical',
    level:    3,
    name:     "BARD (Lore)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     1,
    morale:   0,
    shield:   0,
    effects:  [
      {
        type:         'transform',
        target:       { match: 'type', value: 'starter' },
        replace_with: 'merchant',
        zones:        ['field'],
        selection:    'random',
        fallback:     'none',
      },
    ],
    desc:     'Gain 1 Gold. Transform a random Starter on the field into a Merchant.',
    art:      make_art_painter('tactical'),
  },

  {
    id:       'duelist_captain',
    role:     'tactical',
    level:    3,
    name:     "BARD (Swords)",
    type:     'hero',
    cost:     4,
    atk:      2,
    atk_type: 'physical',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "College of Swords flourish. Deal 2 Physical damage. Gain 2 Gold. Stun a random Monster.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'quartermaster',
    role:     'tactical',
    level:    3,
    name:     "ARTIFICER (Battle Smith)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   3,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "Battle Smith mech-companion. Gain 2 Gold. Gain 3 Defence. Draw 1 card.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'strategist',
    role:     'tactical',
    level:    3,
    name:     "BARD (Valor)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stat_mod_all', stat: 'atk', amount: 2, duration: 'turn' },
    ],
    desc:     "Valor anthem — all Heroes gain +2 ATK this turn.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'spymaster_adept',
    role:     'tactical',
    level:    4,
    name:     "ROGUE (Phantom)",
    type:     'hero',
    cost:     5,
    atk:      3,
    atk_type: 'physical',
    gold:     3,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'weaken_atk', amount: 2 },
    ],
    desc:     "Phantom slips a knife and a secret. Deal 3 Physical damage. Gain 3 Gold. Weaken Big Bad ATK by 2 next turn.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'war_profiteer',
    role:     'tactical',
    level:    4,
    name:     "BARD (Whispers)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'none',
    gold:     5,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "Whispers of insider war news. Gain 5 Gold. Draw 1 card.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'rogue_assassin',
    role:     'tactical',
    level:    4,
    name:     "ROGUE (Assassin)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stop', target_side: 'monster' },
    ],
    desc:     "Assassin strike from the shadow. Deal 4 Physical damage. Gain 2 Gold. Stop a random Monster from acting this turn.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // TACTICAL — Level 5
  // ─────────────────────────────────────────────────────────────

  {
    id:       'shadowlord',
    role:     'tactical',
    level:    5,
    name:     "ROGUE (Soulknife)",
    type:     'hero',
    cost:     6,
    atk:      3,
    atk_type: 'physical',
    gold:     4,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stun', selection: 'opposite' },
      { type: 'weaken_atk', amount: 1 },
    ],
    desc:     "Soulknife mind-blade carves through ranks. Deal 3 Physical damage. Gain 4 Gold. Stun all opposite Monsters. Weaken Big Bad ATK by 1 next turn.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // PHYSICAL — New cards
  // ─────────────────────────────────────────────────────────────

  {
    id:       'shield_warden',
    role:     'physical',
    level:    2,
    name:     "PALADIN (Crown)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   4,
    effects:  [
      { type: 'draw', amount: 1 },
    ],
    desc:     "A Knight of the Crown shields the realm. Gain 4 Defence. Draw 1 card.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'fortress_knight',
    role:     'physical',
    level:    4,
    name:     "FIGHTER (Rune Knight)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   6,
    effects:  [],
    desc:     "Rune Knight invokes giant magic. Deal 4 Physical damage. Gain 6 Defence.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'berserker_lord',
    role:     'physical',
    level:    5,
    name:     "BARBARIAN (Wild Soul)",
    type:     'hero',
    cost:     6,
    atk:      12,
    atk_type: 'physical',
    gold:     0,
    morale:   -4,
    shield:   0,
    effects:  [],
    desc:     "Wild Soul shatters the walls of magic itself. Deal 12 Physical damage. Costs 4 Morale.",
    art:      make_art_painter('physical'),
  },

  // ─────────────────────────────────────────────────────────────
  // MAGICAL — New cards
  // ─────────────────────────────────────────────────────────────

  {
    id:       'battle_healer',
    role:     'magical',
    level:    2,
    name:     "CLERIC (Peace)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'magical',
    gold:     0,
    morale:   4,
    shield:   0,
    effects:  [],
    desc:     "Peace Domain reproach — gentle but firm. Deal 2 Magical damage. Restore 4 Morale.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'storm_caller',
    role:     'magical',
    level:    3,
    name:     "CLERIC (Tempest)",
    type:     'hero',
    cost:     4,
    atk:      6,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'shield_drain', amount: 3 },
    ],
    desc:     "Tempest Domain — lightning shatters armour. Deal 6 Magical damage. Drain 3 Monster Shield.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'battlepriest',
    role:     'magical',
    level:    4,
    name:     "CLERIC (Order)",
    type:     'hero',
    cost:     5,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   4,
    shield:   3,
    effects:  [],
    desc:     "Order Domain — the law strikes, restores, defends. Deal 3 Magical damage. Restore 4 Morale. Gain 3 Defence.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'void_mage',
    role:     'magical',
    level:    5,
    name:     "WARLOCK (Great Old One)",
    type:     'hero',
    cost:     6,
    atk:      4,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'kill_monster', selection: 'random', fallback: 'none' },
      { type: 'draw', amount: 1 },
    ],
    desc:     "Great Old One whispers banishment. Deal 4 Magical damage. Banish a random Monster type. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  // ─────────────────────────────────────────────────────────────
  // TACTICAL — New cards
  // ─────────────────────────────────────────────────────────────

  {
    id:       'city_herald',
    role:     'tactical',
    level:    2,
    name:     "BARD (Eloquence)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     3,
    morale:   3,
    shield:   0,
    effects:  [
      { type: 'weaken_atk', amount: 1 },
    ],
    desc:     "Eloquence rallies the city. Gain 3 Gold. Restore 3 Morale. Weaken Big Bad ATK by 1 next turn.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'siege_engineer',
    role:     'tactical',
    level:    3,
    name:     "ARTIFICER (Artillerist)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'shield_drain', amount: 5 },
      { type: 'draw', amount: 1 },
    ],
    desc:     "Artillerist cannon shears defences. Gain 2 Gold. Drain 5 Monster Shield. Draw 1 card.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // ALLY / COMBO / SCRAP / PIERCE — build-around heroes
  // Reward focused drafting (allies), thoughtful left-to-right placement
  // (combos), one-shot burst (scrap_self), and shield-piercing (pierce).
  // ─────────────────────────────────────────────────────────────

  {
    id:       'iron_legion',
    role:     'physical',
    level:    3,
    name:     "BARBARIAN (Ancestral Guardian)",
    type:     'hero',
    cost:     4,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   1,
    effects:  [
      { type: 'ally_bonus', role: 'physical', stat: 'atk', amount: 3, threshold: 2 },
    ],
    desc:     "Ancestral Guardian — every ancestor joins the strike. Deal 4 Physical damage. Gain 1 Defence. +3 ATK if 2+ Physical heroes are in the field.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'arcane_choir',
    role:     'magical',
    level:    3,
    name:     "BARD (Spirits)",
    type:     'hero',
    cost:     4,
    atk:      2,
    atk_type: 'magical',
    gold:     0,
    morale:   2,
    shield:   0,
    effects:  [
      { type: 'ally_bonus', role: 'magical', stat: 'morale', amount: 4, threshold: 2 },
    ],
    desc:     "Spirits chorus lifts every caster. Deal 2 Magical damage. Restore 2 Morale. +4 Morale if 2+ Magical heroes are in the field.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'merchant_guild',
    role:     'tactical',
    level:    3,
    name:     "BARD (Glamour)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'ally_bonus', role: 'tactical', stat: 'gold', amount: 3, threshold: 2 },
    ],
    desc:     "Glamour inspires the guild. Gain 2 Gold. +3 Gold if 2+ Tactical heroes are in the field.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'shield_wall',
    role:     'physical',
    level:    4,
    name:     "PALADIN (Sentinel)",
    type:     'hero',
    cost:     5,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   3,
    effects:  [
      { type: 'ally_bonus', role: 'physical', stat: 'shield', amount: 5, threshold: 3 },
    ],
    desc:     "Sentinel phalanx — shields lock as one. Deal 2 Physical damage. Gain 3 Defence. +5 Defence if 3+ Physical heroes are in the field.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'vanguard',
    role:     'physical',
    level:    2,
    name:     "FIGHTER (Arcane Archer)",
    type:     'hero',
    cost:     3,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'combo_bonus', requires: 'role', value: 'tactical', stat: 'atk', amount: 3 },
    ],
    desc:     "Arcane Archer's elemental arrow — Deal 2 Physical damage. +3 ATK if a Tactical ally already set up the play.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'executioner',
    role:     'physical',
    level:    4,
    name:     "FIGHTER (Eldritch Knight)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'combo_bonus', requires: 'role', value: 'magical', stat: 'atk', amount: 5 },
    ],
    desc:     "Eldritch Knight finishes what the spell began. Deal 4 Physical damage. +5 ATK if a Magical hero already softened the target.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'opportunist',
    role:     'tactical',
    level:    3,
    name:     "ROGUE (Swashbuckler)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     1,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'combo_bonus', requires: 'role', value: 'physical', stat: 'gold', amount: 3 },
    ],
    desc:     "Swashbuckler reads the gap. Gain 1 Gold. +3 Gold if a Physical hero already drew their attention.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'echo_caster',
    role:     'magical',
    level:    4,
    name:     "SORCERER (Clockwork Soul)",
    type:     'hero',
    cost:     5,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'combo_bonus', requires: 'role', value: 'magical', stat: 'draw', amount: 2 },
    ],
    desc:     "Clockwork Soul resonates with another caster. Deal 3 Magical damage. Draw 2 cards if another Magical hero already resolved.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'siege_breaker',
    role:     'physical',
    level:    3,
    name:     "PALADIN (Conquest)",
    type:     'hero',
    cost:     4,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'pierce' },
    ],
    desc:     "Conquest breaks every wall. Deal 4 Physical damage. Pierce — ignores Monster Shield.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'holy_lance',
    role:     'magical',
    level:    4,
    name:     "PALADIN (Oathkeeper)",
    type:     'hero',
    cost:     5,
    atk:      6,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'pierce' },
    ],
    desc:     "Oathkeeper's radiant lance. Deal 6 Magical damage. Pierce — ignores Monster Shield.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'phoenix_blade',
    role:     'magical',
    level:    5,
    name:     "SORCERER (Phoenix)",
    type:     'hero',
    cost:     5,
    atk:      12,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'pierce' },
      { type: 'scrap_self' },
    ],
    desc:     "Phoenix fire — pure chaotic burst. Deal 12 Magical damage. Pierce. The magic burns them out — banished from your deck after use.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'martyrs_oath',
    role:     'physical',
    level:    2,
    name:     "PALADIN (Redemption)",
    type:     'hero',
    cost:     2,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   4,
    shield:   5,
    effects:  [
      { type: 'scrap_self' },
    ],
    desc:     "Redemption — lay down the sword to save the city. Restore 4 Morale. Gain 5 Defence. Banished from your deck after use.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'black_market',
    role:     'tactical',
    level:    3,
    name:     "WARLOCK (Genie)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     5,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'cost_reduce', amount: 3 },
      { type: 'scrap_self' },
    ],
    desc:     "Genie's wish. Gain 5 Gold. Next recruit costs 3 less Gold. Banished from your deck after use.",
    art:      make_art_painter('tactical'),
  },

  // ─────────────────────────────────────────────────────────────
  // CHAIN / MULTISTRIKE / LIFESTEAL / SACRIFICE / SCALING / BULWARK
  // Reward escalating combos, shield-stripping, sustain, painful trades,
  // late-game burst, and turning blocked attacks into protection.
  // ─────────────────────────────────────────────────────────────

  {
    id:       'war_horn',
    role:     'physical',
    level:    3,
    name:     "PALADIN (Glory)",
    type:     'hero',
    cost:     4,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'chain_bonus', requires: 'role', value: 'physical', stat: 'atk', amount: 2 },
    ],
    desc:     "Glory's rallying cry — Deal 2 Physical damage. +2 ATK per Physical hero already resolved this turn.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'banner_lord',
    role:     'physical',
    level:    4,
    name:     "FIGHTER (Banneret)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'chain_bonus', requires: 'role', value: 'physical', stat: 'atk', amount: 3 },
    ],
    desc:     "Banneret leads the charge. Deal 4 Physical damage. +3 ATK per Physical hero already resolved this turn.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'twin_blade',
    role:     'physical',
    level:    3,
    name:     "FIGHTER (Echo Knight)",
    type:     'hero',
    cost:     4,
    atk:      3,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'multistrike', count: 2 },
    ],
    desc:     "Echo Knight — your spectral duplicate strikes alongside you. Strike twice for 3 Physical damage each.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'arrow_storm',
    role:     'physical',
    level:    4,
    name:     "RANGER (Gloom Stalker)",
    type:     'hero',
    cost:     5,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'multistrike', count: 4 },
    ],
    desc:     "Gloom Stalker volley — shadow arrows tear through armour. Strike four times for 2 Physical damage each.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'fire_rain',
    role:     'magical',
    level:    4,
    name:     "WARLOCK (Celestial)",
    type:     'hero',
    cost:     5,
    atk:      2,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'multistrike', count: 3 },
    ],
    desc:     "Celestial fire rains down. Strike three times for 2 Magical damage each.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'crimson_widow',
    role:     'magical',
    level:    3,
    name:     "WARLOCK (Undead)",
    type:     'hero',
    cost:     4,
    atk:      4,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'lifesteal' },
    ],
    desc:     "Undead pact drinks the foe. Deal 4 Magical damage. Lifesteal — Morale equal to damage dealt.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'vampire_lord',
    role:     'magical',
    level:    5,
    name:     "WARLOCK (Undying)",
    type:     'hero',
    cost:     6,
    atk:      8,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'lifesteal' },
      { type: 'scrap_self' },
    ],
    desc:     "Undying — the final feast. Deal 8 Magical damage. Lifesteal. Banished from your deck after use.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'soul_forge',
    role:     'physical',
    level:    4,
    name:     "WARLOCK (Fathomless)",
    type:     'hero',
    cost:     5,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'sacrifice', target: 'adjacent_starter', stat: 'atk', amount: 6 },
    ],
    desc:     "The Fathomless patron claims a soul. Deal 4 Physical damage. Sacrifice an adjacent Starter for +6 ATK.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'inquisitor',
    role:     'magical',
    level:    4,
    name:     "CLERIC (Death)",
    type:     'hero',
    cost:     5,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'sacrifice', target: 'adjacent_any', stat: 'atk', amount: 5 },
    ],
    desc:     "Death Domain rite — channel the soul of a fallen ally. Deal 3 Magical damage. Sacrifice an adjacent Hero for +5 ATK.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'treasury_knight',
    role:     'tactical',
    level:    3,
    name:     "ROGUE (Swindler)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'scaling_atk', source: 'gold_pool', divisor: 2 },
    ],
    desc:     "Swindler's investment. +1 ATK per 2 Gold in your pool. Hoard, then strike.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'overdraw_mage',
    role:     'magical',
    level:    4,
    name:     "WIZARD (Bladesinging)",
    type:     'hero',
    cost:     5,
    atk:      0,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'scaling_atk', source: 'hand_size', divisor: 1 },
    ],
    desc:     "Bladesinging cascade — every prepared spell becomes a strike. Magical damage equal to cards in your hand.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'last_stand',
    role:     'physical',
    level:    4,
    name:     "PALADIN (Oathbreaker)",
    type:     'hero',
    cost:     4,
    atk:      2,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'scaling_atk', source: 'city_morale_lost', divisor: 3 },
    ],
    desc:     "Oathbreaker's rage fuels the strike. Deal 2 Physical damage. +1 ATK per 3 Morale already lost.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'wall_keeper',
    role:     'physical',
    level:    3,
    name:     "CLERIC (Forge)",
    type:     'hero',
    cost:     4,
    atk:      4,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   2,
    effects:  [
      { type: 'bulwark' },
    ],
    desc:     "Forge Domain — the anvil never breaks. Deal 4 Physical damage. Gain 2 Defence. Bulwark — blocked ATK becomes Defence.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'plague_doctor',
    role:     'tactical',
    level:    4,
    name:     "DRUID (Spores)",
    type:     'hero',
    cost:     4,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   2,
    shield:   0,
    effects:  [
      { type: 'cleanse', zones: ['field', 'hand', 'discard', 'deck'], count: 'all' },
      { type: 'draw',    amount: 1 },
    ],
    desc:     "Spores Druid cleanses rot from the deck. Restore 2 Morale. Cleanse all Corrupted cards. Draw 1 card.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'coin_mage',
    role:     'tactical',
    level:    3,
    name:     "BARD (Creation)",
    type:     'hero',
    cost:     3,
    atk:      0,
    atk_type: 'none',
    gold:     1,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'chain_bonus', requires: 'role', value: 'tactical', stat: 'gold', amount: 2 },
    ],
    desc:     "Creation conjures value from every ally. Gain 1 Gold. +2 Gold per Tactical hero already resolved this turn.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'shadow_broker',
    role:     'tactical',
    level:    5,
    name:     "ROGUE (Arcane Trickster)",
    type:     'hero',
    cost:     6,
    atk:      3,
    atk_type: 'physical',
    gold:     5,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stop', target_side: 'monster' },
      { type: 'weaken_atk', amount: 2 },
    ],
    desc:     "Arcane Trickster seals one foe and pockets the rest. Deal 3 Physical damage. Gain 5 Gold. Stop a random Monster. Weaken Big Bad ATK by 2 next turn.",
    art:      make_art_painter('tactical'),
  },

]);