// cards_upgrades.js
// All promoted hero definitions available in the post-fight upgrade pool.
// Cards are type 'promoted', cost 0, and are never part of the market.
// Do not add engine logic to this file.

const cards_upgrades = [

  {
    id:       'warlord',
    role:     'physical',
    level:    4,
    name:     "BARBARIAN (Totem Warrior)",
    type:     'promoted',
    cost:     0,
    atk:      6,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [],
    desc:     "Totem Warrior — bear-spirit fury. Deal 6 Physical damage.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'archmage',
    role:     'magical',
    level:    5,
    name:     "WIZARD (War Magic)",
    type:     'promoted',
    cost:     0,
    atk:      5,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      {
        type:      'stun',
        selection: 'random',
      },
    ],
    desc:     'Deal 5 Magical damage. Stun a random Monster.',
    art:      make_art_painter('magical'),
  },

  {
    id:       'high_priest',
    role:     'magical',
    level:    4,
    name:     "CLERIC (Life)",
    type:     'promoted',
    cost:     0,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   6,
    shield:   4,
    effects:  [],
    desc:     "Life Domain High Priest. Restore 6 Morale. Gain 4 Defence.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'spymaster',
    role:     'tactical',
    level:    4,
    name:     "ROGUE (Mastermind)",
    type:     'promoted',
    cost:     0,
    atk:      3,
    atk_type: 'physical',
    gold:     3,
    morale:   0,
    shield:   0,
    effects:  [
      {
        type:   'weaken_atk',
        amount: 2,
      },
    ],
    desc:     'Deal 3 Physical damage. Gain 3 Gold. Weaken Enemy ATK by 2.',
    art:      make_art_painter('tactical'),
  },

  {
    id:       'battle_cleric',
    role:     'magical',
    level:    5,
    name:     "CLERIC (Grave)",
    type:     'promoted',
    cost:     0,
    atk:      3,
    atk_type: 'magical',
    gold:     0,
    morale:   3,
    shield:   0,
    effects:  [
      {
        type:      'recur',
        selection: 'random',
      },
    ],
    desc:     'Deal 3 Magical damage. Restore 3 Morale. Recall a random Hero from discard.',
    art:      make_art_painter('magical'),
  },

  {
    id:       'siege_master_upg',
    role:     'physical',
    level:    5,
    name:     "BARBARIAN (Battlerager)",
    type:     'promoted',
    cost:     0,
    atk:      8,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stat_mod_all', stat: 'atk', amount: 2, duration: 'turn' },
    ],
    desc:     "Battlerager Siege Master — every blow rallies the line. Deal 8 Physical damage. All Heroes gain +2 ATK this turn.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'divine_champion_upg',
    role:     'magical',
    level:    5,
    name:     "PALADIN (Devotion)",
    type:     'promoted',
    cost:     0,
    atk:      0,
    atk_type: 'none',
    gold:     0,
    morale:   8,
    shield:   6,
    effects:  [
      { type: 'stun', selection: 'random' },
    ],
    desc:     "Devotion Divine Champion — holy ward and judgement. Restore 8 Morale. Gain 6 Defence. Stun a random Monster.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'assassin_prime',
    role:     'tactical',
    level:    5,
    name:     "ROGUE (Assassin)",
    type:     'promoted',
    cost:     0,
    atk:      5,
    atk_type: 'physical',
    gold:     3,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'stop', target_side: 'monster' },
      { type: 'shield_drain', amount: 4 },
    ],
    desc:     "Assassin perfected. Deal 5 Physical damage. Gain 3 Gold. Stop a random Monster. Drain 4 Monster Shield.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'grand_templar',
    role:     'physical',
    level:    5,
    name:     "PALADIN (Watchers)",
    type:     'promoted',
    cost:     0,
    atk:      5,
    atk_type: 'physical',
    gold:     0,
    morale:   3,
    shield:   4,
    effects:  [
      { type: 'stun', selection: 'opposite' },
    ],
    desc:     "Watchers Grand Templar wards every threat. Deal 5 Physical damage. Restore 3 Morale. Gain 4 Defence. Stun all opposite Monsters.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'iron_marshal',
    role:     'physical',
    level:    5,
    name:     "PALADIN (Conquest)",
    type:     'promoted',
    cost:     0,
    atk:      5,
    atk_type: 'physical',
    gold:     0,
    morale:   0,
    shield:   2,
    effects:  [
      { type: 'ally_bonus', role: 'physical', stat: 'atk', amount: 4, threshold: 2 },
      { type: 'pierce' },
    ],
    desc:     "Conquest paragon — Deal 5 Physical damage. Gain 2 Defence. +4 ATK if 2+ Physical heroes in field. Pierce.",
    art:      make_art_painter('physical'),
  },

  {
    id:       'archon_of_echoes',
    role:     'magical',
    level:    5,
    name:     "WIZARD (Chronurgy)",
    type:     'promoted',
    cost:     0,
    atk:      4,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'combo_bonus', requires: 'role', value: 'magical', stat: 'atk', amount: 5 },
      { type: 'draw', amount: 1 },
    ],
    desc:     "Chronurgy Archon — echoes through time. Deal 4 Magical damage. +5 ATK if a Magical hero already resolved this turn. Draw 1 card.",
    art:      make_art_painter('magical'),
  },

  {
    id:       'guildmaster_prime',
    role:     'tactical',
    level:    5,
    name:     "BARD (Eloquence)",
    type:     'promoted',
    cost:     0,
    atk:      0,
    atk_type: 'none',
    gold:     2,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'ally_bonus', role: 'tactical', stat: 'gold', amount: 5, threshold: 2 },
      { type: 'cost_reduce', amount: 2 },
    ],
    desc:     "Eloquence master orchestrates the guild. Gain 2 Gold. +5 Gold if 2+ Tactical heroes in field. Next recruit costs 2 less Gold.",
    art:      make_art_painter('tactical'),
  },

  {
    id:       'thunder_sage',
    role:     'magical',
    level:    5,
    name:     "CLERIC (Tempest)",
    type:     'promoted',
    cost:     0,
    atk:      6,
    atk_type: 'magical',
    gold:     0,
    morale:   0,
    shield:   0,
    effects:  [
      { type: 'draw', amount: 2 },
      { type: 'weaken_atk', amount: 2 },
    ],
    desc:     "Tempest Domain Thunder Sage — lightning shatters morale. Deal 6 Magical damage. Draw 2 cards. Weaken Big Bad ATK by 2 next turn.",
    art:      make_art_painter('magical'),
  },

];

Registry.register_cards_upgrades(cards_upgrades);
